### ISSUE TITLE
problem building Docker image

### ISSUE THREAD

**Issue by unthingable** [emptyflash/ivor#1]
```
Installing 00lightyear-idx.ibc to /root/.cabal/share/x86_64-linux-ghc-8.0.2/idris-1.0/libs/lightyear
Cloning into 'tomladris'...
Type checking ./Tomladris.idr
Tomladris.idr:87:13:
When checking right hand side of parseToml with expected type
        Parser TomlValue

When checking an application of constructor Tomladris.TTable:
        No such variable mergeLeft
```

Workaround is to add `git checkout` commands for the specific hashes, found in `ivor.toml`, to the Dockerfile.

**Comment by emptyflash** [comment]
Ah yeah, thanks for pointing that out. I've been making some changes to my fork of tomladris, so the dependencies in the Dockerfile should to be locked down to a version.

If you've already made the change, feel free to submit a PR, otherwise I'll probably fix it a little bit later today.
