### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Cynede** [emptyflash/ivor#3]
May you write down small usage example

I'm not asking for full docs but something for newcomers getting started, so people will be able to use it somehow and maybe grow this project :)

**Comment by emptyflash** [comment]
Hey thanks for your interest. I've had some documentation on my list of things to do for a while. Unfortunately I've been distracted by other projects and ivor's been neglected a bit.

If you still wanna get started using ivor, you could try out the docker image, or build it locally with the steps in the dockerfile eg:
```
git clone https://github.com/ziman/lightyear.git 
cd lightyear 
git checkout dbcd847ed7a9e62fa0b502b3d89cca43a96f256c 
idris --install lightyear.ipkg 
cd .. 

git clone https://github.com/emptyflash/tomladris.git 
cd tomladris 
git checkout ec324128ebe8b446e84d8be60b0ed085d07fd36d 
idris --install tomladris.ipkg 
cd .. 

git clone https://github.com/emptyflash/idris-ipkg-parser 
cd idris-ipkg-parser 
git checkout 35cc2f54d4f3b3710f637d0a8c897bfbb32fe183 
idris --install ipkgparser.ipkg 
cd ..

idris --build ivor.ipkg
``` 


That'll give you a executable called `ivor.run`. Then you can create an `ivor.toml` file in the root of your project that looks something like this: https://github.com/emptyflash/ivor/blob/master/ivor.toml

The dependencies look like `user/repo = "git sha"`. Right now it doesn't support transitive dependencies, so you'll have to flatten out your deps and make sure they're in the right order. All the other flags match up with Idris' ipkg file.

Once you have an `ivor.toml` you can run 
 * `./ivor.run install` to install the dependencies, 
 * `./ivor.run build` to build your project,
 * `./ivor.run repl` to hop in the repl with all of your dependencies,
 * `./ivor.run test` to run the tests.

If you have any problems definitely let me know. And feel free to open other issues if you find any bugs. I'll probably write all this up as a getting started guide in the read me at some point.

**Comment by emptyflash** [comment]
whoops didn't mean to hit close D:

**Comment by emptyflash** [comment]
I added my write up to the readme and cleaned it up a bit. I'd still like to get some more documentation out, like a tour of the source code and IdrisDocs at some point.

**Comment by Cynede** [comment]
aww... I promise to review it tomo... on this or second week!
